/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImagePanel.java
 *
 * Created on 14.11.2010, 09:58:20
 */
package rccontrol;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author David
 */
public class ImagePanel extends javax.swing.JPanel {

    public static BufferedImage image;
    private static int border = 0;

    @Override
    public void paintComponent(Graphics g) {

        if (image != null) {
            g.drawImage(image, border, border, getWidth() - border*2,
                    getHeight() - border*2, null);
        } else {

 //           System.out.println("    paintComponent: no image available, image == null? " + (image == null));
        }
    }

    public void setImage(BufferedImage in) {
        image = in;
        repaint();
    }

    /** Creates new form ImagePanel */
    public ImagePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
