/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * videoPanel.java
 *
 * Created on 13.11.2010, 20:45:20
 */

package rccontrol;

import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author David
 */
public class videoPanel extends javax.swing.JPanel {

    public Image image;

    /** Creates new form videoPanel */
    public videoPanel() {
        initComponents();
    }

    public void setImage(Image in){
        image = in;
        this.repaint();
    }

    @Override
    public void paintComponent(Graphics g){
        g.drawImage(image, 0, 0,this.getWidth(), this.getHeight(), null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
